version: "2"

services:

  frontend:
    restart: "no"
    image: talek
    volumes:
      - ./:/talek_net
    command: talekfrontend  --client /talek_net/talek.json --common /talek_net/common.json -l ":8080" --verbose
    network_mode: host
    depends_on:
      - replica1
      - replica2
      - replica3

  replica1:
    restart: "no"
    image: talek
    volumes:
      - ./:/talek_net
    command: talekreplica -f /talek_net/common.json -l ":8081" -c /talek_net/replica1.json
    network_mode: host

  replica2:
    restart: "no"
    image: talek
    volumes:
      - ./:/talek_net
    command: talekreplica -f /talek_net/common.json -l ":8082" -c /talek_net/replica2.json
    network_mode: host

  replica3:
    restart: "no"
    image: talek
    volumes:
      - ./:/talek_net
    command: talekreplica -f /talek_net/common.json -l ":8083" -c /talek_net/replica3.json
    network_mode: host
